api: "1.19"
name: MiningIUT
version: "0.8.1"
author: Daxelarne
main: daxelarne.knightworld.MiningIUT.Main
api-version: 1.19

commands:
  xpbottle:
     usage: xpbottle [<player> <amount>]
     permission: xpbotte.xpbottle
     
permissions:
  xpbotte.xpbottle:
    description: Permet de se give des bouteilles d'xp